# This configuration files contains all the informations required for processing
# smFISH dataset from .nd2 file to single hybridization stitching


# Name of the analysis run
analysis_name :  'TestingAnalysis'

# Parameters for image filtering and raw counting

# Genes and tags to skip for the raw counting
skip_genes_counting : ['Background','Nuclei']

skip_tags_counting : ['_IF']

# Decide if to run illumination correction before filtering
illumination_correction : False

# Minimal disptance in pxl between peaks for dot calling
min_distance : 3

# Stringency to use for dots calling. Stringency : 0 use the calculated
# threshold
stringency : 0

# Number of planes to remove

plane_keep : None

# Parameter that will be used if the processed files will be saved in the ram
use_ram : True

# Max size of RAM to fill with tmp files
max_ram : 5000000000



# -------------------------------------------------------------------------
# Stitching parameters

# Stitch the image in 2D or 3D (3D need more work/testing)
nr_dim : 2

# Number of peaks to use for the alignment
nr_peaks : 8

# Determine if the coords need to be flipped

y_flip : False

# Method to use for blending
# can be 'linear' or 'non linear'
# The methods that performs the best is the 'non linear'

blend : 'non linear'

# Reference gene for stitching
reference_gene : 'Nuclei'

# -------------------------------------------------------------------------
# Apply stitching parameters

hybs_to_stitch : ['Hybridization2']
