# This file contains the parameters for the segmentation of the immuno
# staining

# The configuration are grouped according to the staining to process

  polyT :
    # Parameters for image chunking
    image_chunking_parameters:
    
      chunk_size : 1000
      # Overlapping between processing chunks
      percent_padding : 0.1

    segmentation_parameters:
      # Define the trimming point define a Thr for image processing
      trimming : -4
      # minimum size of the object in order to be labelled
      min_object_size : 500 
      # disk radius for the ranking filter
      disk_radium_rank_filer : 1
      # minimum distance between peaks for the creation of the markers for the
      # first round of watershed
      min_distance : 10
      # relative threshold between the markers for the first round of watershed
      threshold_rel : 0.8
      
